version: '3.7'

services:

  create-clients:
    build: .
    volumes:
      - ./hydra-clients.json:/hydra-clients.json
      - ./randoms.json:/randoms.json
      - ./output:/output
    restart: on-failure
    command: |-
      bash -c "rm -r /output/* && cat /hydra-clients.json | /create_hydra_clients.sh && cat /randoms.json | /random.sh"
    networks:
      - trusted

networks:
  trusted:
    name: "trusted"
